"""initial schema

Revision ID: d6f33576a36f
Revises: 
Create Date: 2026-05-25 19:03:21.126693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f33576a36f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('tipo_solicitacao', sa.String(length=100), nullable=False),
    sa.Column('valor_patrimonio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('prioridade', sa.String(length=40), nullable=True),
    sa.Column('pipefy_card_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_table('processed_webhook_events',
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('card_id', sa.String(length=100), nullable=False),
    sa.Column('cliente_email', sa.String(length=320), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_webhook_events')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
